/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface": "#1b1b1b",
        "tertiary-container": "#484843",
        "primary-fixed-dim": "#9dd3aa",
        "surface-container-low": "#f6f3f2",
        "primary-fixed": "#b9efc5",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#5d4200",
        "primary-container": "#1f5132",
        "error-container": "#ffdad6",
        "surface-container-highest": "#e5e2e1",
        "primary": "#023a1d",
        "secondary": "#7b5800",
        "inverse-surface": "#313030",
        "surface-dim": "#dcd9d9",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#f0bf60",
        "on-secondary-container": "#785600",
        "inverse-on-surface": "#f3f0ef",
        "surface-bright": "#fcf9f8",
        "surface-variant": "#e5e2e1",
        "on-secondary-fixed": "#271900",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#1c1c18",
        "on-primary-fixed-variant": "#1e5031",
        "background": "#fcf9f8",
        "surface-container": "#f0eded",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#474742",
        "tertiary-fixed-dim": "#c9c6c0",
        "on-error-container": "#93000a",
        "secondary-container": "#ffcd6d",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "tertiary": "#32322d",
        "on-primary-fixed": "#00210e",
        "secondary-fixed": "#ffdea5",
        "on-background": "#1b1b1b",
        "on-surface-variant": "#414942",
        "surface-tint": "#376847",
        "outline-variant": "#c1c9bf",
        "on-tertiary-container": "#b8b6b0",
        "tertiary-fixed": "#e5e2db",
        "inverse-primary": "#9dd3aa",
        "outline": "#717971",
        "surface-container-high": "#eae7e7",
        "on-primary-container": "#8ec39b",
        "surface": "#fcf9f8"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "24px",
        "stack-xl": "48px",
        "margin-mobile": "16px",
        "margin-desktop": "5vw",
        "container-max": "100%",
        "unit": "8px",
        "stack-md": "16px",
        "stack-xs": "4px",
        "gutter": "24px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "label-sm": ["12px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
